apiVersion: v1
kind: Pod
metadata:
  name: webapp-blue
  namespace: production
  labels:
    name: web
spec:
  containers:
    - name: web
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: blue
